name: dinov2-extras
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pip

  - pytorch=2.0.0
  - torchvision=0.15.0
  - pytorch-cuda=11.8

  - cmake
  - ninja
  - make
  - gxx_linux-64
  - gcc_linux-64

  - omegaconf
  - torchmetrics=0.10.3
  - fvcore
  - iopath

  - pip:
    - git+https://github.com/facebookincubator/submitit

